### ISSUE TITLE
多列关联选择有问题，比如省市地区选择，第二级有两个“朝阳”，第三级的数据就不对了

### ISSUE THREAD

**Issue by Hext123** [jaykon/KKPicker#2]
首先感谢楼主开源分享；

具体问题是联动的时候根据`key`查下一级，但是可能会出现`key`一样的情况；

问题数据：

    北京->朝阳
    辽宁->朝阳

目前我把北京的`朝阳`改成`朝阳区`了

**Comment by jaykon** [comment]
是有这个问题，我尽快修复下

**Comment by jaykon** [comment]
使用新的数据结构，这个问题已经在最新的提交处解决。
